import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/layouts/Navbar";
import {Footer} from "@/components/layouts/Footer";
import StoreProvider from "@/store/Provider";
import {ToastsContainer} from "@/components/commons/Toasts";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
        </head>
        <body className={inter.className}>
        <Navbar/>

        <StoreProvider>
            {children}
            <ToastsContainer/>
        </StoreProvider>
        <Footer/>
        </body>
        </html>
    );
}
